//! Local-only governed writes. MCP deliberately does not expose this module.
use crate::snapshots::{root,child,names,write_new,publish,compute_sha256};
use crate::vault::{frontmatter,valid_frontmatter};
use cap_std::fs::{Dir,OpenOptions,OpenOptionsExt};
use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
use std::{path::Path,os::fd::AsRawFd,io::Read,collections::BTreeMap};
const INDEX:&str="M7_STATE.json";
const JOURNAL:&str="M7_PENDING.json";
const MAX:usize=512*1024;
fn err(e:impl std::fmt::Display)->String{e.to_string()}
#[derive(Clone,Serialize,Deserialize,Debug)]
#[serde(rename_all="camelCase",deny_unknown_fields)]
pub struct Revision{pub revision:u32,pub relative_path:String,pub sha256:String,pub created_at:String}
#[derive(Clone,Serialize,Deserialize,Debug)]
#[serde(rename_all="camelCase",deny_unknown_fields)]
pub struct Item{pub id:String,pub kind:String,pub title:String,pub category:String,pub workflow_status:String,pub revisions:Vec<Revision>,pub sources:Vec<Value>,pub origin:String,pub provider:Option<String>,pub model:Option<String>,pub decision:Option<Value>}
#[derive(Clone,Serialize,Deserialize,Debug)]
#[serde(rename_all="camelCase",deny_unknown_fields)]
pub struct State{pub version:u32,pub generation:u64,pub items:BTreeMap<String,Item>,pub operations:BTreeMap<String,String>}
impl Default for State{fn default()->Self{Self{version:2,generation:0,items:BTreeMap::new(),operations:BTreeMap::new()}}}
#[derive(Clone,Serialize,Deserialize,Debug)]
#[serde(rename_all="camelCase",deny_unknown_fields)]
pub struct Request{pub action:String,#[serde(default)]pub operation_id:String,#[serde(default)]pub id:String,#[serde(default)]pub revision:u32,#[serde(default)]pub expected_sha256:String,#[serde(default)]pub title:String,#[serde(default)]pub category:String,#[serde(default)]pub content:String,#[serde(default)]pub source_path:String,#[serde(default)]pub target_path:String,#[serde(default)]pub reason:String,#[serde(default)]pub provider:Option<String>,#[serde(default)]pub model:Option<String>,#[serde(default)]pub sources:Vec<Value>}
#[derive(Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
struct Pending{base:u64,next:State,document:Option<(String,String)>}
fn parts(p:&str)->Result<Vec<&str>,String>{let v:Vec<_>=p.split('/').collect();if v.iter().any(|x|x.is_empty()||x.starts_with('.')||x.contains(['\\','\0'])){Err("Unsafe path".into())}else{Ok(v)}}
fn category(k:&str)->Result<&'static str,String>{Ok(match k{"client"=>"01_CLIENTS","project"=>"02_PROJECTS","brand"=>"03_BRANDS","positioning"=>"04_POSITIONING","packaging"=>"05_PACKAGING_KNOWLEDGE","method"=>"06_METHODS","case_study"=>"07_CASE_STUDIES","research"=>"08_MARKET_RESEARCH","competitor"=>"09_COMPETITORS","approved_output"=>"10_APPROVED_OUTPUTS",_=>return Err("Invalid official category".into())})}
fn check_path(p:&str,folder:&str)->Result<(),String>{let v=parts(p)?;if v.len()<2||v[0]!=folder||!p.ends_with(".md"){return Err("Document outside allowed category".into())}Ok(())}
fn bounded(d:&Dir,p:&str)->Result<Vec<u8>,String>{let ps=parts(p)?;let mut dir=d.try_clone().map_err(err)?;for n in &ps[..ps.len()-1]{dir=child(&dir,n)?;}let mut f=dir.open_with(ps[ps.len()-1],OpenOptions::new().read(true).custom_flags(libc::O_NOFOLLOW|libc::O_NONBLOCK)).map_err(err)?;let m=f.metadata().map_err(err)?;if !m.is_file()||m.len()>MAX as u64{return Err("Invalid or oversized document".into())}let mut b=Vec::new();std::io::Read::by_ref(&mut f).take(MAX as u64+1).read_to_end(&mut b).map_err(err)?;let a=f.metadata().map_err(err)?;if b.len()>MAX||m.len()!=a.len()||m.modified().map_err(err)?!=a.modified().map_err(err)?{return Err("Document changed during read".into())}Ok(b)}
fn digest(s:&str)->bool{s.len()==64&&s.bytes().all(|c|c.is_ascii_digit()||(b'a'..=b'f').contains(&c))}
fn validate(s:&State)->Result<(),String>{if s.version!=2||s.items.len()>10000||s.operations.len()>20000{return Err("Unsupported/oversized M7 state".into())}for(id,i)in &s.items{if id!=&i.id||!digest(id)||!['o','p'].iter().any(|c|i.kind.starts_with(*c))||!["output","proposal"].contains(&i.kind.as_str())||!["pending","approved","rejected"].contains(&i.workflow_status.as_str())||i.revisions.is_empty(){return Err("Invalid M7 item".into())}if i.kind=="proposal"{category(&i.category)?;}for(n,r)in i.revisions.iter().enumerate(){check_path(&r.relative_path,if i.kind=="output"{"80_AI_OUTPUTS"}else{"90_PROPOSALS"})?;if r.revision as usize!=n+1||!digest(&r.sha256){return Err("Invalid revision".into())}}}Ok(())}
fn load(system:&Dir)->Result<State,String>{if !names(system)?.contains(&INDEX.into()){return Ok(State::default())}let b=bounded(system,INDEX)?;let s=serde_json::from_slice(&b).map_err(err)?;validate(&s)?;Ok(s)}
fn atomic(system:&Dir,name:&str,b:&[u8])->Result<(),String>{let mut random=[0;16];getrandom::fill(&mut random).map_err(err)?;let stage=format!(".m7-{}",compute_sha256(&random));write_new(system,&stage,b)?;system.rename(&stage,system,name).map_err(err)}
fn document(d:&Dir,path:&str,bytes:&[u8])->Result<(),String>{let ps=parts(path)?;let mut dir=d.try_clone().map_err(err)?;for p in &ps[..ps.len()-1]{dir=child(&dir,p)?;}let name=ps[ps.len()-1];if names(&dir)?.contains(&name.into()){if bounded(d,path)?==bytes{return Ok(())}return Err("Existing destination differs; no overwrite".into())}let stage=format!(".m7-{}",compute_sha256(bytes));if !names(&dir)?.contains(&stage){write_new(&dir,&stage,bytes)?;}else if crate::snapshots::read(&dir,&stage)?!=bytes{return Err("Staging conflict".into())}publish(&dir,&stage,name)}
fn recover(d:&Dir,system:&Dir,s:&State,checkpoint:fn(&str))->Result<State,String>{let pending:Pending=serde_json::from_slice(&bounded(system,JOURNAL)?).map_err(err)?;validate(&pending.next)?;if pending.next.generation!=pending.base+1||!(s.generation==pending.base||s.generation==pending.next.generation){return Err("Journal generation conflict".into())}if let Some((p,text))=&pending.document{let f=frontmatter(text)?.ok_or("Missing frontmatter")?;let typ=f["type"].as_str().ok_or("Missing type")?;check_path(p,match typ{"ai_output"=>"80_AI_OUTPUTS","proposal"=>"90_PROPOSALS",_=>category(typ)?})?;let h=compute_sha256(text.as_bytes());let linked=pending.next.items.values().any(|i|i.revisions.iter().any(|r|r.relative_path==*p&&r.sha256==h)||i.decision.as_ref().is_some_and(|v|v["targetPath"]==*p&&v["publishedSha256"]==h));if !linked{return Err("Journal document not linked to state".into())}document(d,p,text.as_bytes())?;checkpoint("document");}atomic(system,INDEX,&serde_json::to_vec_pretty(&pending.next).map_err(err)?)?;checkpoint("index");system.remove_file(JOURNAL).map_err(err)?;Ok(pending.next)}
fn redact(s:&str)->String{regex::Regex::new(r"sk-[A-Za-z0-9_-]{12,}").unwrap().replace_all(s,"[REDACTED_API_KEY]").into_owned()}
fn markdown(id:&str,title:&str,typ:&str,status:&str,content:&str,sources:&[Value])->Result<String,String>{let now=chrono::Utc::now().to_rfc3339();let fm=json!({"schema_version":1,"id":id,"title":redact(title),"type":typ,"client":"","project":"","status":status,"created_at":now,"updated_at":now,"tags":[],"source_ids":sources.iter().filter_map(|s|s["documentId"].as_str().or_else(||s["sourceId"].as_str())).collect::<Vec<_>>()});if !valid_frontmatter(&fm){return Err("Invalid frontmatter".into())}Ok(format!("---\n{}---\n{}\n",serde_yaml::to_string(&fm).map_err(err)?,redact(content)))}
fn result(d:&Dir,s:&State)->Result<Value,String>{let mut items=Vec::new();for i in s.items.values(){let mut v=serde_json::to_value(i).map_err(err)?;let mut versions=Vec::new();for r in &i.revisions{let bytes=bounded(d,&r.relative_path)?;if compute_sha256(&bytes)!=r.sha256{return Err(format!("Revision changed: {}",r.relative_path))}versions.push(json!({"revision":r.revision,"markdown":String::from_utf8(bytes).map_err(err)?}));}v["versions"]=json!(versions);v["sourceWarnings"]=json!(i.sources.iter().filter_map(|src|{let Some(p)=src["relativePath"].as_str()else{return Some("Source reference has no path; provenance is incomplete".into())};let valid=src["sha256"].as_str().and_then(|h|bounded(d,p).ok().map(|b|compute_sha256(&b)==h)).unwrap_or(false);if valid{None}else{Some(format!("Source missing, changed or not verified: {p}"))}}).collect::<Vec<_>>());if i.sources.is_empty(){v["sourceWarnings"]=json!(["No source references available; provenance is incomplete"]);}items.push(v);}Ok(json!({"version":s.version,"generation":s.generation,"items":items,"reindexRequired":true}))}
pub fn execute(path:&Path,q:Request)->Result<Value,String>{execute_with_checkpoint(path,q,|_|{})}
// Used by the native test harness to kill its own process at actual persistence boundaries.
// The Tauri command always calls execute with a no-op checkpoint.
pub fn execute_with_checkpoint(path:&Path,mut q:Request,checkpoint:fn(&str))->Result<Value,String>{if q.content.len()>MAX/2||q.sources.len()>50||q.title.len()>300||q.reason.len()>2000{return Err("M7 input limit".into())}for source in &mut q.sources{let object=source.as_object_mut().ok_or("Invalid source reference")?;object.retain(|k,_|["documentId","sourceId","relativePath","sha256","title","category","status"].contains(&k.as_str()));for value in object.values_mut(){let text=value.as_str().ok_or("Source fields must be strings")?;if text.len()>2048{return Err("Source field oversized".into())}*value=json!(redact(text));}}if let Some(model)=&mut q.model{if model.len()>200{return Err("Model name oversized".into())}*model=redact(model);}let d=root(path)?;let system=child(&d,"00_SYSTEM")?;
 let lock=system.open_with(".m7-lock",OpenOptions::new().read(true).write(true).create(true).custom_flags(libc::O_NOFOLLOW|libc::O_NONBLOCK)).map_err(err)?;if !lock.metadata().map_err(err)?.is_file(){return Err("Invalid lock".into())}if unsafe{libc::flock(lock.as_raw_fd(),libc::LOCK_EX|libc::LOCK_NB)}!=0{return Err("Another M7 operation is active; retry".into())}
 let mut s=load(&system)?;
 if names(&system)?.contains(&JOURNAL.into()){if q.action!="recover"{return Err("Interrupted operation pending. Review and use Recover operation.".into())}s=recover(&d,&system,&s,checkpoint)?;return result(&d,&s)}
 if q.action=="list"||q.action=="recover"{return result(&d,&s)}
 if !digest(&q.operation_id){return Err("A 64-character operation ID is required".into())}let fingerprint=compute_sha256(&serde_json::to_vec(&q).map_err(err)?);if let Some(old)=s.operations.get(&q.operation_id){if old!=&fingerprint{return Err("Operation ID reused with different input".into())}return result(&d,&s)}
 let base=s.generation;let now=chrono::Utc::now().to_rfc3339();let mut doc=None;
 match q.action.as_str(){
 "save"|"create"|"import"=>{let id=q.operation_id.clone();let kind=if q.action=="save"{"output"}else{"proposal"};let mut sources=q.sources.clone();let mut content=q.content.clone();let mut origin="local human input".to_string();if q.action=="save"{if q.provider.as_deref()!=Some("openai")||q.model.as_deref().unwrap_or("").is_empty(){return Err("Provider/model provenance required".into())}origin="OpenAI response explicitly saved locally".into();}
 if q.action=="import"{check_path(&q.source_path,"90_PROPOSALS")?;let bytes=bounded(&d,&q.source_path)?;if compute_sha256(&bytes)!=q.expected_sha256{return Err("M4 draft changed since preview".into())}let text=String::from_utf8(bytes).map_err(err)?;frontmatter(&text)?.ok_or("Missing draft frontmatter")?;content=text;origin=format!("Explicit import of {}",q.source_path);sources.push(json!({"relativePath":q.source_path,"sha256":q.expected_sha256}));}
 if !q.id.is_empty(){let source=s.items.get(&q.id).ok_or("Unknown source output")?;let r=source.revisions.last().unwrap();if source.kind!="output"||r.sha256!=q.expected_sha256{return Err("Source output changed".into())}let bytes=bounded(&d,&r.relative_path)?;if compute_sha256(&bytes)!=r.sha256{return Err("Output changed on disk".into())}content=String::from_utf8(bytes).map_err(err)?;sources=source.sources.clone();q.provider=source.provider.clone();q.model=source.model.clone();origin=format!("Saved output {}",source.id);}
 if kind=="proposal"{category(&q.category)?;}if q.title.trim().is_empty()||content.trim().is_empty(){return Err("Title and content required".into())}let text=markdown(&id,&q.title,if kind=="output"{"ai_output"}else{"proposal"},"draft",&content,&sources)?;let rel=format!("{}/{}-r1.md",if kind=="output"{"80_AI_OUTPUTS"}else{"90_PROPOSALS"},id);let revision=Revision{revision:1,relative_path:rel.clone(),sha256:compute_sha256(text.as_bytes()),created_at:now};s.items.insert(id.clone(),Item{id,kind:kind.into(),title:redact(&q.title),category:q.category.clone(),workflow_status:"pending".into(),revisions:vec![revision],sources,origin,provider:q.provider.clone(),model:q.model.clone(),decision:None});doc=Some((rel,text));},
 "revise"|"approve"|"reject"=>{let item=s.items.get_mut(&q.id).ok_or("Unknown proposal")?;if item.kind!="proposal"||item.workflow_status!="pending"{return Err("Only pending proposals may be decided".into())}let latest=item.revisions.last().unwrap().clone();if latest.revision!=q.revision||latest.sha256!=q.expected_sha256||compute_sha256(&bounded(&d,&latest.relative_path)?)!=latest.sha256{return Err("Proposal changed; review current revision".into())}
 if q.action=="revise"{if q.content.trim().is_empty(){return Err("Empty revision".into())}let n=latest.revision+1;let text=markdown(&q.id,&item.title,"proposal","draft",&q.content,&item.sources)?;let rel=format!("90_PROPOSALS/{}-r{n}.md",q.id);item.revisions.push(Revision{revision:n,relative_path:rel.clone(),sha256:compute_sha256(text.as_bytes()),created_at:now});doc=Some((rel,text));}
 else if q.action=="reject"{if q.reason.trim().is_empty(){return Err("Rejection reason required".into())}item.workflow_status="rejected".into();item.decision=Some(json!({"action":"reject","reason":redact(&q.reason),"revision":q.revision,"sha256":q.expected_sha256,"at":now,"actor":"local human action"}));}
 else {check_path(&q.target_path,category(&item.category)?)?;let ps=parts(&q.target_path)?;let mut dir=d.try_clone().map_err(err)?;for p in &ps[..ps.len()-1]{dir=child(&dir,p)?;}if names(&dir)?.contains(&ps[ps.len()-1].into()){return Err("Destination exists; overwrite forbidden".into())}let reviewed=bounded(&d,&latest.relative_path)?;if compute_sha256(&reviewed)!=latest.sha256{return Err("Proposal changed before publication".into())}let original=String::from_utf8(reviewed).map_err(err)?;let (_,body)=original.strip_prefix("---\n").ok_or("Invalid frontmatter")?.split_once("\n---\n").ok_or("Invalid frontmatter")?;let text=markdown(&q.id,&item.title,&item.category,"approved",body,&item.sources)?;item.workflow_status="approved".into();item.decision=Some(json!({"action":"approve","revision":q.revision,"sha256":q.expected_sha256,"targetPath":q.target_path,"publishedSha256":compute_sha256(text.as_bytes()),"at":now,"actor":"local human action"}));doc=Some((q.target_path.clone(),text));}},
 _=>return Err("Unknown M7 action".into())}
 s.generation+=1;s.operations.insert(q.operation_id,fingerprint);validate(&s)?;
 let pending=Pending{base,next:s,document:doc};let journal_bytes=serde_json::to_vec_pretty(&pending).map_err(err)?;if journal_bytes.len()>MAX{return Err("M7 state capacity reached; no changes written".into())}write_new(&system,JOURNAL,&journal_bytes)?;checkpoint("journal");let loaded=load(&system)?;let next=recover(&d,&system,&loaded,checkpoint)?;result(&d,&next)
}
#[cfg(test)]mod tests{
 use super::*;use tempfile::TempDir;use std::fs;
 fn fixture()->TempDir{let t=TempDir::new().unwrap();for p in ["00_SYSTEM","80_AI_OUTPUTS","90_PROPOSALS","01_CLIENTS","20_RAW_SOURCES"]{fs::create_dir(t.path().join(p)).unwrap()}t}
 fn q(action:&str,n:u8)->Request{serde_json::from_value(json!({"action":action,"operationId":format!("{n:064x}")})).unwrap()}
 fn proposal(t:&TempDir,n:u8)->(Request,Value){let mut r=q("create",n);r.title="Review àèé".into();r.category="client".into();r.content="Version one".into();let v=execute(t.path(),r.clone()).unwrap();(r,v)}
 fn decision(v:&Value,action:&str,n:u8)->Request{let i=&v["items"][0];let r=i["revisions"].as_array().unwrap().last().unwrap();let mut q=q(action,n);q.id=i["id"].as_str().unwrap().into();q.revision=r["revision"].as_u64().unwrap() as u32;q.expected_sha256=r["sha256"].as_str().unwrap().into();q}
 #[test]fn m7_metadata_secrets_and_output_provenance(){let t=fixture();let mut r=q("save",9);r.title="Saved".into();r.content="Output".into();r.provider=Some("openai".into());r.model=Some("test-model".into());r.sources=vec![json!({"documentId":"source","relativePath":"01_CLIENTS/missing.md","sha256":"0".repeat(64),"title":"sk-1234567890123456","apiKey":"sk-1234567890123456"})];let v=execute(t.path(),r).unwrap();let state=fs::read_to_string(t.path().join("00_SYSTEM/M7_STATE.json")).unwrap();assert!(!state.contains("sk-1234567890123456"));assert!(!state.contains("apiKey"));assert!(!v["items"][0]["sourceWarnings"].as_array().unwrap().is_empty());let mut p=q("create",10);p.id=v["items"][0]["id"].as_str().unwrap().into();p.expected_sha256=v["items"][0]["revisions"][0]["sha256"].as_str().unwrap().into();p.title="Review".into();p.category="client".into();let out=execute(t.path(),p).unwrap();let proposal=out["items"].as_array().unwrap().iter().find(|i|i["kind"]=="proposal").unwrap();assert_eq!(proposal["model"],"test-model");assert_eq!(proposal["provider"],"openai");}
 #[test]fn m7_revisions_exclusive_approval_and_idempotence(){let t=fixture();let (r,v)=proposal(&t,1);assert_eq!(execute(t.path(),r).unwrap(),v);let old=v["items"][0]["revisions"][0]["relativePath"].as_str().unwrap();let bytes=fs::read(t.path().join(old)).unwrap();let mut revise=decision(&v,"revise",2);revise.content="Version two".into();let v2=execute(t.path(),revise).unwrap();assert_eq!(fs::read(t.path().join(old)).unwrap(),bytes);assert_eq!(v2["items"][0]["revisions"].as_array().unwrap().len(),2);let mut stale=decision(&v,"approve",3);stale.target_path="01_CLIENTS/a.md".into();assert!(execute(t.path(),stale).is_err());let mut approve=decision(&v2,"approve",4);approve.target_path="01_CLIENTS/a.md".into();let accepted=execute(t.path(),approve.clone()).unwrap();assert_eq!(execute(t.path(),approve).unwrap(),accepted);assert_eq!(frontmatter(&fs::read_to_string(t.path().join("01_CLIENTS/a.md")).unwrap()).unwrap().unwrap()["status"],"approved");assert_eq!(fs::read_dir(t.path().join("20_RAW_SOURCES")).unwrap().count(),0);}
 #[test]fn m7_raw_collision_symlink_and_changed_bytes_denied(){let t=fixture();let(_,v)=proposal(&t,1);let mut a=decision(&v,"approve",2);a.target_path="20_RAW_SOURCES/bad.md".into();assert!(execute(t.path(),a.clone()).is_err());a.target_path="01_CLIENTS/existing.md".into();fs::write(t.path().join(&a.target_path),"Existing").unwrap();assert!(execute(t.path(),a.clone()).is_err());assert_eq!(fs::read_to_string(t.path().join(&a.target_path)).unwrap(),"Existing");let outside=TempDir::new().unwrap();std::os::unix::fs::symlink(outside.path(),t.path().join("01_CLIENTS/link")).unwrap();a.target_path="01_CLIENTS/link/bad.md".into();assert!(execute(t.path(),a.clone()).is_err());let p=v["items"][0]["revisions"][0]["relativePath"].as_str().unwrap();fs::write(t.path().join(p),"Changed").unwrap();a.target_path="01_CLIENTS/new.md".into();assert!(execute(t.path(),a).is_err());}
 #[test]fn m7_import_keeps_compiler_draft_and_rejection(){let t=fixture();let source="90_PROPOSALS/compiler.md";let text=markdown("source","Compiler","proposal","draft","Raw-derived",&[]).unwrap();fs::write(t.path().join(source),&text).unwrap();let mut r=q("import",5);r.source_path=source.into();r.expected_sha256=compute_sha256(text.as_bytes());r.category="client".into();r.title="Imported".into();let v=execute(t.path(),r).unwrap();let mut reject=decision(&v,"reject",6);reject.reason="Needs review".into();let v2=execute(t.path(),reject).unwrap();assert_eq!(v2["items"][0]["workflowStatus"],"rejected");assert_eq!(fs::read_to_string(t.path().join(source)).unwrap(),text);assert!(execute(t.path(),decision(&v2,"approve",7)).is_err());}
 #[test]fn m7_corrupt_state_and_journal_preserved(){let t=fixture();fs::write(t.path().join("00_SYSTEM/M7_STATE.json"),"{bad").unwrap();assert!(execute(t.path(),q("list",1)).is_err());assert_eq!(fs::read_to_string(t.path().join("00_SYSTEM/M7_STATE.json")).unwrap(),"{bad");fs::remove_file(t.path().join("00_SYSTEM/M7_STATE.json")).unwrap();fs::write(t.path().join("00_SYSTEM/M7_PENDING.json"),"{bad").unwrap();assert!(execute(t.path(),q("recover",1)).is_err());assert!(t.path().join("00_SYSTEM/M7_PENDING.json").exists());}
 #[test]fn m7_recovery_after_document_published(){let t=fixture();let (_,v)=proposal(&t,1);let d=root(t.path()).unwrap();let system=child(&d,"00_SYSTEM").unwrap();let before=load(&system).unwrap();let mut next=before.clone();next.generation+=1;let id=v["items"][0]["id"].as_str().unwrap();let text=markdown(id,"Reviewed","client","approved","Recovered",&[]).unwrap();let h=compute_sha256(text.as_bytes());next.items.get_mut(id).unwrap().workflow_status="approved".into();next.items.get_mut(id).unwrap().decision=Some(json!({"targetPath":"01_CLIENTS/recovered.md","publishedSha256":h}));let p=Pending{base:before.generation,next,document:Some(("01_CLIENTS/recovered.md".into(),text.clone()))};write_new(&system,JOURNAL,&serde_json::to_vec(&p).unwrap()).unwrap();document(&d,"01_CLIENTS/recovered.md",text.as_bytes()).unwrap();assert!(execute(t.path(),q("list",1)).is_err());let recovered=execute(t.path(),q("recover",1)).unwrap();assert_eq!(recovered["generation"],2);assert_eq!(fs::read_to_string(t.path().join("01_CLIENTS/recovered.md")).unwrap(),text);assert!(!t.path().join("00_SYSTEM/M7_PENDING.json").exists());}
}
