import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {LocalSearchEngine} from '../../../packages/search-engine/src/index.js';import {ContextSelector} from '../../../packages/ai-engine/src/context-selector.js';
const root=path.resolve(import.meta.dirname,'../../..');const exe=process.env.LIMEN_M6_BIN||path.join(root,'apps/desktop/src-tauri/target/debug/limen-vault');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'limen-m6-e2e-'));const vault=fs.realpathSync(temp);
const sha=(b:string|Buffer)=>createHash('sha256').update(b).digest('hex');
try{
 for(const d of ['00_SYSTEM','01_CLIENTS','90_PROPOSALS','20_RAW_SOURCES'])fs.mkdirSync(path.join(vault,d));
 for(const [name,status,text] of [['approved','approved','Project Aurora launch is 17 October 2026. Verification phrase: blue espresso.'],['draft','draft','Project Aurora launch is 99 October.'],['review','review','Project Aurora secret review.']])fs.writeFileSync(path.join(vault,`01_CLIENTS/${name}.md`),`---\nid: ${name}\ntitle: Aurora ${name}\nstatus: ${status}\nclient: Acme\nproject: Aurora\ntags: [launch]\n---\n${text}\n`);
 fs.writeFileSync(path.join(vault,'20_RAW_SOURCES/private.txt'),'MUST NOT BE EXPOSED');
 await new LocalSearchEngine().indexVault(vault);
 const baseline=Object.fromEntries(fs.readdirSync(path.join(vault,'01_CLIENTS')).map(f=>[f,sha(fs.readFileSync(path.join(vault,'01_CLIENTS',f)))]));const index=fs.readFileSync(path.join(vault,'00_SYSTEM/SEARCH_INDEX.json'));
 const selected=await new ContextSelector().selectContext(vault,{provider:'openai',prompt:'Aurora'});assert.equal(selected.sources.length,1);const s=selected.sources[0];const id=sha(vault);
 const request=(id:number,method:string,params:unknown)=>({jsonrpc:'2.0',id,method,params});
 const messages=[request(1,'initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'m6-native-e2e',version:'1'}}),{jsonrpc:'2.0',method:'notifications/initialized'},request(2,'tools/list',{}),request(3,'tools/call',{name:'list_vaults',arguments:{}}),request(4,'tools/call',{name:'search_vault',arguments:{vault_id:id,term:'Aurora'}}),request(5,'tools/call',{name:'read_document',arguments:{vault_id:id,document_id:s.id,sha256:s.sha256}}),request(6,'tools/call',{name:'read_document',arguments:{vault_id:'wrong',document_id:s.id,sha256:s.sha256}}),request(7,'tools/call',{name:'write_document',arguments:{vault_id:id}}),request(8,'tools/call',{name:'read_document',arguments:{vault_id:id,document_id:'../../etc/passwd',sha256:'a'.repeat(64)}})];
 const run=spawnSync(exe,['--mcp-stdio',vault],{input:messages.map(x=>JSON.stringify(x)).join('\n')+'\n',encoding:'utf8',timeout:30000,env:{...process.env,PATH:'/usr/bin:/bin'}});assert.equal(run.status,0,run.stderr);const responses=run.stdout.trim().split('\n').map(s=>JSON.parse(s));const get=(id:number)=>responses.find(r=>r.id===id).result;assert.equal(get(2).tools.length,3);assert.ok(get(2).tools.every((t:any)=>t.annotations.readOnlyHint));assert.equal(JSON.parse(get(3).content[0].text)[0].id,id);const hits=JSON.parse(get(4).content[0].text);assert.equal(hits.length,1);assert.equal(hits[0].sha256,s.sha256);const doc=JSON.parse(get(5).content[0].text);assert.equal(doc.content,s.content);assert.equal(doc.documentId,s.id);for(const id of [6,7,8])assert.equal(get(id).isError,true);for(const [f,hash] of Object.entries(baseline))assert.equal(sha(fs.readFileSync(path.join(vault,'01_CLIENTS',f))),hash);assert.deepEqual(fs.readFileSync(path.join(vault,'00_SYSTEM/SEARCH_INDEX.json')),index);
 const forged=JSON.parse(index.toString());const draft=forged.documents['01_CLIENTS/draft.md'];draft.status='approved';fs.writeFileSync(path.join(vault,'00_SYSTEM/SEARCH_INDEX.json'),JSON.stringify(forged));
 const probe=spawnSync(exe,['--mcp-stdio',vault],{input:[messages[0],request(20,'tools/call',{name:'read_document',arguments:{vault_id:id,document_id:draft.id,sha256:draft.sha256}})].map(x=>JSON.stringify(x)).join('\n')+'\n',encoding:'utf8',timeout:30000});assert.equal(probe.status,0,probe.stderr);assert.equal(JSON.parse(probe.stdout.trim().split('\n').at(-1)!).result.isError,true,'Forged approval must be rejected by the release binary');fs.writeFileSync(path.join(vault,'00_SYSTEM/SEARCH_INDEX.json'),index);
 console.log('PASS M6 native stdio: TS/M5 source parity, protocol lifecycle, real search/read, approval policy, isolation, traversal/write denial, no Node, unchanged source/index hashes.');
}finally{fs.rmSync(temp,{recursive:true,force:true});}
