import test from 'node:test';import assert from 'node:assert/strict';import worker,{sha,canonical} from './worker.mjs';
class Bucket{
 objects=new Map();counter=0;
 async get(key){const v=this.objects.get(key);return v?{etag:v.etag,size:v.bytes.length,body:v.bytes,json:async()=>JSON.parse(new TextDecoder().decode(v.bytes)),arrayBuffer:async()=>v.bytes}:null;}
 async put(key,value,options={}){const existing=this.objects.get(key);const cond=options.onlyIf;if(cond?.etagMatches && existing?.etag!==cond.etagMatches)return null;if(cond instanceof Headers&&cond.get('If-None-Match')==='*'&&existing)return null;const bytes=typeof value==='string'?new TextEncoder().encode(value):new Uint8Array(value);this.objects.set(key,{bytes,etag:String(++this.counter)});return {etag:String(this.counter)};}
}
async function fixture(){const token='fixture-token-never-production';const grant={tokenHash:await sha(token),tenantId:'qa',vaultId:'vault',channels:['private','published'],write:true,expiresAt:'2099-01-01T00:00:00Z'};const env={VAULT:new Bucket(),ACCESS_GRANTS:JSON.stringify([grant])};const request=(path,method='GET',body,auth=token)=>worker.fetch(new Request('https://fixture/v1/'+path,{method,headers:{Authorization:'Bearer '+auth},body}),env);const content='---\nstatus: approved\n---\nSynthetic fixture';const h=await sha(content);const m={schemaVersion:1,formatVersion:1,channel:'published',tenantId:'qa',vaultId:'vault',releaseId:'r1',parentReleaseId:null,deviceId:'d1',createdAt:'2026-09-13T00:00:00Z',documents:[{id:'a',relativePath:'01_CLIENTS/a.md',sha256:h,objectRef:h,sizeBytes:new TextEncoder().encode(content).length,category:'01_CLIENTS',status:'approved'}]};m.manifestHash=await sha(canonical(m));return{env,request,content,h,m};}
test('Gateway denies unknown identity and private channel without grant',async()=>{const f=await fixture();assert.equal((await f.request('status','GET',undefined,'invalid')).status,403);const g=JSON.parse(f.env.ACCESS_GRANTS);g[0].channels=['published'];f.env.ACCESS_GRANTS=JSON.stringify(g);assert.equal((await f.request('private/current')).status,403);});
test('Gateway verifies objects, idempotent commit, CAS conflict, pinned read and revoke',async()=>{const f=await fixture();assert.equal((await f.request('published/commit','POST',JSON.stringify(f.m))).status,400);assert.equal((await f.request('published/object/'+f.h,'PUT','corrupt')).status,400);assert.equal((await f.request('published/object/'+f.h,'PUT',f.content)).status,200);assert.equal((await f.request('published/commit','POST',JSON.stringify(f.m))).status,200);assert.equal((await f.request('published/commit','POST',JSON.stringify(f.m))).status,200);const next={...f.m,releaseId:'r2'};delete next.manifestHash;next.manifestHash=await sha(canonical(next));assert.equal((await f.request('published/commit','POST',JSON.stringify(next))).status,409);assert.equal(await(await f.request('published/release/r1/'+f.h)).text(),f.content);assert.deepEqual((await(await f.request('published/releases')).json()).map(x=>x.releaseId),['r1']);assert.equal((await f.request('published/revoke','POST')).status,200);assert.equal((await f.request('published/release/r1/'+f.h)).status,403);assert.equal((await f.request('published/commit','POST',JSON.stringify(f.m))).status,409);});
test('Gateway rejects cross tenant and path collision before writing',async()=>{const f=await fixture();f.m.tenantId='other';delete f.m.manifestHash;f.m.manifestHash=await sha(canonical(f.m));assert.equal((await f.request('published/commit','POST',JSON.stringify(f.m))).status,400);assert.equal(f.env.VAULT.objects.size,0);});

test('Gateway refuses a manifest committed through the other channel',async()=>{const f=await fixture();assert.equal((await f.request('private/commit','POST',JSON.stringify(f.m))).status,400);assert.equal(f.env.VAULT.objects.size,0);});

test('Temporary storage failure is retryable without exposing internals',async()=>{const f=await fixture();f.env.VAULT.get=async()=>{throw Error('private infrastructure detail');};const r=await f.request('private/current');assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'STORAGE_UNAVAILABLE'});});
