import {labelIt, MessageIt} from './locale';
import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
const folders:Record<string,string>={all:'all',clients:'01_CLIENTS',projects:'02_PROJECTS',brands:'03_BRANDS',positioning:'04_POSITIONING',packaging:'05_PACKAGING_KNOWLEDGE',methods:'06_METHODS',case_studies:'07_CASE_STUDIES',research:'08_MARKET_RESEARCH',competitors:'09_COMPETITORS',approved_outputs:'10_APPROVED_OUTPUTS'};
type Note={automationKind?:string;relativePath:string;title:string;status:string;sha256:string;markdown:string};
export function KnowledgePanel({vaultPath,category}:{vaultPath:string;category:string}){
 const [notes,setNotes]=useState<Note[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let live=true;setBusy(true);setError('');setNotes([]);void invoke<Note[]>('list_knowledge',{vaultPath,folder:folders[category]}).then(r=>{if(live)setNotes(r)}).catch(e=>{if(live)setError(String(e))}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[vaultPath,category,refresh]);
 return <div className="limen-card" style={{padding:24}}><h3>{category==='all'?'Tutte le note':labelIt(category)}</h3>{category!=='all'&&<p><code>{folders[category]}</code></p>}<p>Legge direttamente i file Markdown locali. Non richiede indice di ricerca né connessione di rete.</p><button disabled={busy} onClick={()=>setRefresh(n=>n+1)}>AGGIORNA CONOSCENZA</button>{busy?<p role="status">Caricamento delle note locali...</p>:error?<p role="alert">{<MessageIt value={error}/>}</p>:notes.length===0?<p>Nessuna nota Markdown in questa vista. I file caricati restano in Fonti finché l’automazione non li elabora. Le bozze della compilazione manuale si trovano in Proposte. Puoi scegliere Tutte le note per consultare tutte le categorie.</p>:notes.map(n=><details key={n.relativePath}><summary>{n.title} · {n.automationKind==='wiki'?'Wiki AI':n.automationKind==='source'?'Fonte elaborata automaticamente':labelIt(n.status)} · {n.relativePath}</summary><p style={{overflowWrap:'anywhere'}}>SHA-256 {n.sha256}</p><pre style={{whiteSpace:'pre-wrap'}}>{n.markdown}</pre></details>)}</div>
}
